language: node_js
node_js:
  - "6"
  - "4"
services:
  - mysql
env:
  global:
    - DATABASE_HOST=localhost
    - DATABASE_USER=travis
before_script:
  - mysql -e 'create database cronduty;'
  - npm run migrations
cache:
  directories:
    - node_modules
notifications:
  email: false
