language: node_js
node_js:
  - "node"
  - "6"
before_script:
  - mysql -e 'create database cronduty;'
  - npm run migrations
cache:
  directories:
    - node_modules
services:
  - mysql
notifications:
  email: false
